name: olympiade
description: Offizielle App der Wuerzburger Olympiade
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  firebase_database: ^11.1.4
  firebase_core: ^3.5.0
  flutter_launcher_icons: ^0.14.0
  intl: ^0.19.0
  confetti: ^0.7.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  animated_flip_counter: ^0.3.4
  flame: ^1.19.0
  flame_audio: ^2.10.3
  starsview: ^0.0.2
  provider: ^6.1.2
  awesome_notifications: ^0.9.3+1
  url_launcher: ^6.0.20
  infinite_carousel: ^1.1.1
  shimmer: ^3.0.0
  wakelock_plus: ^1.2.8
  just_audio: ^0.9.40
  audio_service: ^0.18.15
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/play_store_512.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/achievements/
    - assets/icon/
    - assets/fonts/
    - assets/dice/