name: olympiade
description: Offizielle App der Würzburger Olympiade
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  firebase_database: ^10.2.4
  firebase_core: ^2.15.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  audioplayers: ^5.1.0
  confetti: ^0.7.0
  audioplayers_darwin: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/